#####
#####
##### comments
name: First-test-workflow
on: 
  push:
    branches: 
      - master
jobs: 
  Print-message-one:
    runs-on: ubuntu-latest
    steps:
    - name: First message
      run : Echo "Hello workflow"
   
  Print-message-two:
    runs-on: ubuntu-latest
    steps:
    - name: Second message
      run : Echo "You did it"
